import React, {useEffect,useRef} from 'react';
import {X,LoaderCircle,ArrowRight,GraduationCap} from 'lucide-react';
export function Button({children,variant='primary',className='',busy=false,icon:Icon,...props}) {return <button className={`btn btn-${variant} ${className}`} disabled={busy||props.disabled} {...props}>{busy?<LoaderCircle size={17} className="spin"/>:Icon?<Icon size={17}/>:null}{children}</button>;}
export function Field({label,children,hint,...props}) {return <label className="field"><span>{label}</span>{children||<input {...props}/>} {hint&&<small>{hint}</small>}</label>;}
export function Empty({icon:Icon=GraduationCap,title,children,action}) {return <div className="empty"><div className="empty-icon"><Icon size={30}/></div><h3>{title}</h3><p>{children}</p>{action}</div>;}
export function Modal({title,children,onClose,wide=false}) {
 const ref=useRef(null),closeRef=useRef(onClose);closeRef.current=onClose;
 useEffect(()=>{const previous=document.activeElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.focus();const key=e=>{if(e.key==='Escape')closeRef.current?.();if(e.key==='Tab'){const els=ref.current?.querySelectorAll('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex="0"]');if(!els?.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===ref.current)){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',key);previous?.focus();};},[]);
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose?.();}}><section ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-label={title} className={`modal ${wide?'wide':''}`}><div className="modal-heading"><h2>{title}</h2>{onClose&&<button className="icon-btn" onClick={onClose} aria-label="Close dialog"><X size={21}/></button>}</div>{children}</section></div>;
}
export function SectionHeading({eyebrow,title,description,action}) {return <div className="section-heading"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2>{description&&<p>{description}</p>}</div>{action}</div>;}
export function Brand({settings,onClick}) {return <button className="brand" onClick={onClick} aria-label="Sure60 home">{settings.logo_url?<img src={settings.logo_url} alt={settings.brand} className="custom-logo"/>:<><span className="brand-mark"><GraduationCap size={26}/></span><span>{settings.brand?.replace(/60$/,'')}<b>{settings.brand?.endsWith('60')?'60':''}</b><small>LEARN. BELIEVE. ACHIEVE.</small></span></>}</button>;}
export function TextLink({children,...props}) {return <button className="text-link" {...props}>{children}<ArrowRight size={16}/></button>;}
